// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ProfileTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void profile() {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/panel/garage");
    driver.Manage().Window.Size = new System.Drawing.Size(1050, 840);
    driver.FindElement(By.Id("userNavDropdown")).Click();
    driver.FindElement(By.LinkText("Profile")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
  }
}
